version: '3.8'
services:
  app:
    container_name: nodejs2024Q1-service
    # restart: always
    # environment:
      # - PORT=${PORT}
      # - DATABASE_URL=12312312312312312
    build:
      context: .
      dockerfile: docker/Dockerfile.service
      args:
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - app-network  

  postgres:
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
      args:
        DBPORT: ${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network  

volumes:
  postgres:

networks:
  app-network:
    driver: bridge