version: '3.8'
services:
  app:
    container_name: nodejs2024Q1-service
    restart: always
    environment:
    - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres
    build:
      context: .
      dockerfile: docker/Dockerfile.service
      args:
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network  

  postgres:
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
      args:
        DBPORT: ${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5  
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - app-network  

volumes:
  postgres:

networks:
  app-network:
    driver: bridge